/**
 * Seed: food_items
 * ~150 aliments base interne — 6 catégories × sous-types
 * Idempotent via ON CONFLICT (item_key) DO UPDATE
 *
 * Usage: npx tsx scripts/seed-food-items.ts
 */

import { createClient } from "@supabase/supabase-js";

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!,
);

type FoodItemSeed = {
  item_key: string;
  name_fr: string;
  category_l1:
    | "proteins"
    | "carbs"
    | "vegetables"
    | "fruits"
    | "fats"
    | "extras";
  category_l2: string;
  kcal_per_100g: number;
  protein_per_100g: number;
  carbs_per_100g: number;
  fat_per_100g: number;
  fiber_per_100g: number;
};

const FOOD_ITEMS: FoodItemSeed[] = [
  // ──────────────────────────────────────────────
  // PROTÉINES — Viandes (bœuf)
  // ──────────────────────────────────────────────
  {
    item_key: "chicken-breast",
    name_fr: "Poulet blanc (cuit)",
    category_l1: "proteins",
    category_l2: "viandes",
    kcal_per_100g: 165,
    protein_per_100g: 31,
    carbs_per_100g: 0,
    fat_per_100g: 3.6,
    fiber_per_100g: 0,
  },
  {
    item_key: "chicken-thigh",
    name_fr: "Poulet cuisse (cuit)",
    category_l1: "proteins",
    category_l2: "viandes",
    kcal_per_100g: 209,
    protein_per_100g: 26,
    carbs_per_100g: 0,
    fat_per_100g: 11,
    fiber_per_100g: 0,
  },
  {
    item_key: "beef-mince-5pct",
    name_fr: "Bœuf haché 5% MG",
    category_l1: "proteins",
    category_l2: "viandes",
    kcal_per_100g: 137,
    protein_per_100g: 21,
    carbs_per_100g: 0,
    fat_per_100g: 5,
    fiber_per_100g: 0,
  },
  {
    item_key: "beef-mince-15pct",
    name_fr: "Bœuf haché 15% MG",
    category_l1: "proteins",
    category_l2: "viandes",
    kcal_per_100g: 215,
    protein_per_100g: 17,
    carbs_per_100g: 0,
    fat_per_100g: 15,
    fiber_per_100g: 0,
  },
  {
    item_key: "beef-steak",
    name_fr: "Steak bœuf (cuit)",
    category_l1: "proteins",
    category_l2: "viandes",
    kcal_per_100g: 210,
    protein_per_100g: 28,
    carbs_per_100g: 0,
    fat_per_100g: 10,
    fiber_per_100g: 0,
  },
  {
    item_key: "beef-entrecote",
    name_fr: "Entrecôte de bœuf (cuite)",
    category_l1: "proteins",
    category_l2: "viandes",
    kcal_per_100g: 295,
    protein_per_100g: 24,
    carbs_per_100g: 0,
    fat_per_100g: 22,
    fiber_per_100g: 0,
  },
  {
    item_key: "beef-faux-filet",
    name_fr: "Faux-filet de bœuf (cuit)",
    category_l1: "proteins",
    category_l2: "viandes",
    kcal_per_100g: 207,
    protein_per_100g: 27,
    carbs_per_100g: 0,
    fat_per_100g: 11,
    fiber_per_100g: 0,
  },
  {
    item_key: "beef-bavette",
    name_fr: "Bavette de bœuf (cuite)",
    category_l1: "proteins",
    category_l2: "viandes",
    kcal_per_100g: 185,
    protein_per_100g: 28,
    carbs_per_100g: 0,
    fat_per_100g: 8,
    fiber_per_100g: 0,
  },
  {
    item_key: "beef-cote",
    name_fr: "Côte de bœuf (cuite)",
    category_l1: "proteins",
    category_l2: "viandes",
    kcal_per_100g: 300,
    protein_per_100g: 23,
    carbs_per_100g: 0,
    fat_per_100g: 23,
    fiber_per_100g: 0,
  },
  {
    item_key: "beef-roast",
    name_fr: "Rôti de bœuf (cuit)",
    category_l1: "proteins",
    category_l2: "viandes",
    kcal_per_100g: 215,
    protein_per_100g: 28,
    carbs_per_100g: 0,
    fat_per_100g: 12,
    fiber_per_100g: 0,
  },

  // ──────────────────────────────────────────────
  // PROTÉINES — Viandes (autres)
  // ──────────────────────────────────────────────
  {
    item_key: "pork-tenderloin",
    name_fr: "Filet mignon de porc",
    category_l1: "proteins",
    category_l2: "viandes",
    kcal_per_100g: 143,
    protein_per_100g: 22,
    carbs_per_100g: 0,
    fat_per_100g: 5.5,
    fiber_per_100g: 0,
  },
  {
    item_key: "turkey-breast",
    name_fr: "Dinde blanc (cuit)",
    category_l1: "proteins",
    category_l2: "viandes",
    kcal_per_100g: 135,
    protein_per_100g: 29,
    carbs_per_100g: 0,
    fat_per_100g: 1,
    fiber_per_100g: 0,
  },
  {
    item_key: "lamb-leg",
    name_fr: "Gigot d'agneau (cuit)",
    category_l1: "proteins",
    category_l2: "viandes",
    kcal_per_100g: 191,
    protein_per_100g: 28,
    carbs_per_100g: 0,
    fat_per_100g: 8.5,
    fiber_per_100g: 0,
  },
  {
    item_key: "veal-escalope",
    name_fr: "Escalope de veau (cuite)",
    category_l1: "proteins",
    category_l2: "viandes",
    kcal_per_100g: 175,
    protein_per_100g: 28,
    carbs_per_100g: 0,
    fat_per_100g: 7,
    fiber_per_100g: 0,
  },
  {
    item_key: "duck-magret",
    name_fr: "Magret de canard (cuit, sans peau)",
    category_l1: "proteins",
    category_l2: "viandes",
    kcal_per_100g: 190,
    protein_per_100g: 23,
    carbs_per_100g: 0,
    fat_per_100g: 10,
    fiber_per_100g: 0,
  },
  {
    item_key: "beef-liver",
    name_fr: "Foie de veau (cuit)",
    category_l1: "proteins",
    category_l2: "viandes",
    kcal_per_100g: 155,
    protein_per_100g: 24,
    carbs_per_100g: 5,
    fat_per_100g: 5,
    fiber_per_100g: 0,
  },
  {
    item_key: "ham-cooked",
    name_fr: "Jambon blanc (cuit)",
    category_l1: "proteins",
    category_l2: "viandes",
    kcal_per_100g: 107,
    protein_per_100g: 18,
    carbs_per_100g: 1,
    fat_per_100g: 4,
    fiber_per_100g: 0,
  },
  {
    item_key: "ham-dry",
    name_fr: "Jambon sec / cru",
    category_l1: "proteins",
    category_l2: "viandes",
    kcal_per_100g: 250,
    protein_per_100g: 30,
    carbs_per_100g: 0.5,
    fat_per_100g: 15,
    fiber_per_100g: 0,
  },
  {
    item_key: "lardons-smoked",
    name_fr: "Lardons fumés",
    category_l1: "proteins",
    category_l2: "viandes",
    kcal_per_100g: 340,
    protein_per_100g: 22,
    carbs_per_100g: 0.5,
    fat_per_100g: 28,
    fiber_per_100g: 0,
  },

  // ──────────────────────────────────────────────
  // PROTÉINES — Poissons frais
  // ──────────────────────────────────────────────
  {
    item_key: "salmon-fillet",
    name_fr: "Saumon (cuit)",
    category_l1: "proteins",
    category_l2: "poissons",
    kcal_per_100g: 208,
    protein_per_100g: 20,
    carbs_per_100g: 0,
    fat_per_100g: 13,
    fiber_per_100g: 0,
  },
  {
    item_key: "salmon-smoked",
    name_fr: "Saumon fumé",
    category_l1: "proteins",
    category_l2: "poissons",
    kcal_per_100g: 142,
    protein_per_100g: 25,
    carbs_per_100g: 0,
    fat_per_100g: 4.5,
    fiber_per_100g: 0,
  },
  {
    item_key: "tuna-fresh",
    name_fr: "Thon frais (cuit)",
    category_l1: "proteins",
    category_l2: "poissons",
    kcal_per_100g: 184,
    protein_per_100g: 30,
    carbs_per_100g: 0,
    fat_per_100g: 6,
    fiber_per_100g: 0,
  },
  {
    item_key: "cod-fillet",
    name_fr: "Cabillaud (cuit)",
    category_l1: "proteins",
    category_l2: "poissons",
    kcal_per_100g: 105,
    protein_per_100g: 23,
    carbs_per_100g: 0,
    fat_per_100g: 1,
    fiber_per_100g: 0,
  },
  {
    item_key: "trout-fillet",
    name_fr: "Truite (cuite)",
    category_l1: "proteins",
    category_l2: "poissons",
    kcal_per_100g: 190,
    protein_per_100g: 22,
    carbs_per_100g: 0,
    fat_per_100g: 11,
    fiber_per_100g: 0,
  },
  {
    item_key: "sea-bass",
    name_fr: "Bar / Loup de mer (cuit)",
    category_l1: "proteins",
    category_l2: "poissons",
    kcal_per_100g: 124,
    protein_per_100g: 24,
    carbs_per_100g: 0,
    fat_per_100g: 3,
    fiber_per_100g: 0,
  },
  {
    item_key: "sea-bream",
    name_fr: "Dorade royale (cuite)",
    category_l1: "proteins",
    category_l2: "poissons",
    kcal_per_100g: 133,
    protein_per_100g: 22,
    carbs_per_100g: 0,
    fat_per_100g: 5,
    fiber_per_100g: 0,
  },
  {
    item_key: "tilapia",
    name_fr: "Tilapia (cuit)",
    category_l1: "proteins",
    category_l2: "poissons",
    kcal_per_100g: 128,
    protein_per_100g: 26,
    carbs_per_100g: 0,
    fat_per_100g: 3,
    fiber_per_100g: 0,
  },
  {
    item_key: "sole-fillet",
    name_fr: "Sole (cuite)",
    category_l1: "proteins",
    category_l2: "poissons",
    kcal_per_100g: 92,
    protein_per_100g: 20,
    carbs_per_100g: 0,
    fat_per_100g: 1.2,
    fiber_per_100g: 0,
  },
  {
    item_key: "pollock-fillet",
    name_fr: "Lieu noir (cuit)",
    category_l1: "proteins",
    category_l2: "poissons",
    kcal_per_100g: 92,
    protein_per_100g: 21,
    carbs_per_100g: 0,
    fat_per_100g: 0.8,
    fiber_per_100g: 0,
  },
  {
    item_key: "mackerel-fillet",
    name_fr: "Maquereau (cuit)",
    category_l1: "proteins",
    category_l2: "poissons",
    kcal_per_100g: 262,
    protein_per_100g: 19,
    carbs_per_100g: 0,
    fat_per_100g: 20,
    fiber_per_100g: 0,
  },
  {
    item_key: "herring-fillet",
    name_fr: "Hareng (mariné)",
    category_l1: "proteins",
    category_l2: "poissons",
    kcal_per_100g: 230,
    protein_per_100g: 16,
    carbs_per_100g: 2,
    fat_per_100g: 17,
    fiber_per_100g: 0,
  },
  {
    item_key: "shrimp",
    name_fr: "Crevettes (cuites)",
    category_l1: "proteins",
    category_l2: "poissons",
    kcal_per_100g: 99,
    protein_per_100g: 24,
    carbs_per_100g: 0,
    fat_per_100g: 0.3,
    fiber_per_100g: 0,
  },
  {
    item_key: "mussels",
    name_fr: "Moules (cuites)",
    category_l1: "proteins",
    category_l2: "poissons",
    kcal_per_100g: 86,
    protein_per_100g: 12,
    carbs_per_100g: 3.7,
    fat_per_100g: 2.2,
    fiber_per_100g: 0,
  },

  // ──────────────────────────────────────────────
  // PROTÉINES — Poissons en boîte
  // ──────────────────────────────────────────────
  {
    item_key: "tuna-canned",
    name_fr: "Thon en boîte (au naturel)",
    category_l1: "proteins",
    category_l2: "poissons",
    kcal_per_100g: 116,
    protein_per_100g: 25,
    carbs_per_100g: 0,
    fat_per_100g: 1,
    fiber_per_100g: 0,
  },
  {
    item_key: "tuna-canned-oil",
    name_fr: "Thon en boîte (à l'huile, égoutté)",
    category_l1: "proteins",
    category_l2: "poissons",
    kcal_per_100g: 200,
    protein_per_100g: 25,
    carbs_per_100g: 0,
    fat_per_100g: 11,
    fiber_per_100g: 0,
  },
  {
    item_key: "sardines-canned",
    name_fr: "Sardines en boîte (huile égouttée)",
    category_l1: "proteins",
    category_l2: "poissons",
    kcal_per_100g: 208,
    protein_per_100g: 25,
    carbs_per_100g: 0,
    fat_per_100g: 11,
    fiber_per_100g: 0,
  },
  {
    item_key: "mackerel-canned-tomato",
    name_fr: "Maquereau en boîte (sauce tomate)",
    category_l1: "proteins",
    category_l2: "poissons",
    kcal_per_100g: 170,
    protein_per_100g: 17,
    carbs_per_100g: 3,
    fat_per_100g: 10,
    fiber_per_100g: 0,
  },
  {
    item_key: "anchovies-canned",
    name_fr: "Anchois (en boîte)",
    category_l1: "proteins",
    category_l2: "poissons",
    kcal_per_100g: 210,
    protein_per_100g: 29,
    carbs_per_100g: 0.8,
    fat_per_100g: 10,
    fiber_per_100g: 0,
  },

  // ──────────────────────────────────────────────
  // PROTÉINES — Œufs
  // ──────────────────────────────────────────────
  {
    item_key: "whole-egg",
    name_fr: "Œuf entier",
    category_l1: "proteins",
    category_l2: "oeufs",
    kcal_per_100g: 155,
    protein_per_100g: 13,
    carbs_per_100g: 1.1,
    fat_per_100g: 11,
    fiber_per_100g: 0,
  },
  {
    item_key: "egg-white",
    name_fr: "Blanc d'œuf",
    category_l1: "proteins",
    category_l2: "oeufs",
    kcal_per_100g: 52,
    protein_per_100g: 11,
    carbs_per_100g: 0.7,
    fat_per_100g: 0.2,
    fiber_per_100g: 0,
  },

  // ──────────────────────────────────────────────
  // PROTÉINES — Produits laitiers
  // ──────────────────────────────────────────────
  {
    item_key: "cottage-cheese",
    name_fr: "Cottage cheese",
    category_l1: "proteins",
    category_l2: "laitiers",
    kcal_per_100g: 98,
    protein_per_100g: 11,
    carbs_per_100g: 3.4,
    fat_per_100g: 4.3,
    fiber_per_100g: 0,
  },
  {
    item_key: "fromage-blanc-0pct",
    name_fr: "Fromage blanc 0%",
    category_l1: "proteins",
    category_l2: "laitiers",
    kcal_per_100g: 44,
    protein_per_100g: 8,
    carbs_per_100g: 4,
    fat_per_100g: 0.1,
    fiber_per_100g: 0,
  },
  {
    item_key: "skyr",
    name_fr: "Skyr nature",
    category_l1: "proteins",
    category_l2: "laitiers",
    kcal_per_100g: 63,
    protein_per_100g: 11,
    carbs_per_100g: 4,
    fat_per_100g: 0.2,
    fiber_per_100g: 0,
  },
  {
    item_key: "greek-yogurt",
    name_fr: "Yaourt grec nature",
    category_l1: "proteins",
    category_l2: "laitiers",
    kcal_per_100g: 97,
    protein_per_100g: 9,
    carbs_per_100g: 3.6,
    fat_per_100g: 5,
    fiber_per_100g: 0,
  },
  {
    item_key: "ricotta",
    name_fr: "Ricotta",
    category_l1: "proteins",
    category_l2: "laitiers",
    kcal_per_100g: 174,
    protein_per_100g: 11,
    carbs_per_100g: 3,
    fat_per_100g: 13,
    fiber_per_100g: 0,
  },

  // ──────────────────────────────────────────────
  // PROTÉINES — Végétales
  // ──────────────────────────────────────────────
  {
    item_key: "tofu-firm",
    name_fr: "Tofu ferme",
    category_l1: "proteins",
    category_l2: "vegetales",
    kcal_per_100g: 144,
    protein_per_100g: 17,
    carbs_per_100g: 3,
    fat_per_100g: 8,
    fiber_per_100g: 0.3,
  },
  {
    item_key: "tempeh",
    name_fr: "Tempeh",
    category_l1: "proteins",
    category_l2: "vegetales",
    kcal_per_100g: 195,
    protein_per_100g: 19,
    carbs_per_100g: 9,
    fat_per_100g: 11,
    fiber_per_100g: 0,
  },
  {
    item_key: "edamame",
    name_fr: "Edamame (cuit)",
    category_l1: "proteins",
    category_l2: "vegetales",
    kcal_per_100g: 122,
    protein_per_100g: 11,
    carbs_per_100g: 10,
    fat_per_100g: 5,
    fiber_per_100g: 5,
  },
  {
    item_key: "seitan",
    name_fr: "Seitan",
    category_l1: "proteins",
    category_l2: "vegetales",
    kcal_per_100g: 370,
    protein_per_100g: 75,
    carbs_per_100g: 14,
    fat_per_100g: 2,
    fiber_per_100g: 0.6,
  },

  // ──────────────────────────────────────────────
  // PROTÉINES — Compléments
  // ──────────────────────────────────────────────
  {
    item_key: "whey-protein",
    name_fr: "Whey protéine (poudre)",
    category_l1: "proteins",
    category_l2: "complements",
    kcal_per_100g: 380,
    protein_per_100g: 80,
    carbs_per_100g: 7,
    fat_per_100g: 5,
    fiber_per_100g: 0,
  },
  {
    item_key: "casein-protein",
    name_fr: "Caséine (poudre)",
    category_l1: "proteins",
    category_l2: "complements",
    kcal_per_100g: 370,
    protein_per_100g: 80,
    carbs_per_100g: 5,
    fat_per_100g: 3,
    fiber_per_100g: 0,
  },
  {
    item_key: "plant-isolate",
    name_fr: "Isolat végétal (pois/riz)",
    category_l1: "proteins",
    category_l2: "complements",
    kcal_per_100g: 370,
    protein_per_100g: 78,
    carbs_per_100g: 7,
    fat_per_100g: 4,
    fiber_per_100g: 2,
  },

  // ──────────────────────────────────────────────
  // GLUCIDES — Céréales
  // ──────────────────────────────────────────────
  {
    item_key: "white-rice",
    name_fr: "Riz blanc (cuit)",
    category_l1: "carbs",
    category_l2: "cereales",
    kcal_per_100g: 130,
    protein_per_100g: 2.7,
    carbs_per_100g: 28,
    fat_per_100g: 0.3,
    fiber_per_100g: 0.4,
  },
  {
    item_key: "brown-rice",
    name_fr: "Riz brun (cuit)",
    category_l1: "carbs",
    category_l2: "cereales",
    kcal_per_100g: 111,
    protein_per_100g: 2.6,
    carbs_per_100g: 23,
    fat_per_100g: 0.9,
    fiber_per_100g: 1.8,
  },
  {
    item_key: "oats-raw",
    name_fr: "Flocons d'avoine (crus)",
    category_l1: "carbs",
    category_l2: "cereales",
    kcal_per_100g: 389,
    protein_per_100g: 17,
    carbs_per_100g: 66,
    fat_per_100g: 7,
    fiber_per_100g: 10,
  },
  {
    item_key: "quinoa",
    name_fr: "Quinoa (cuit)",
    category_l1: "carbs",
    category_l2: "cereales",
    kcal_per_100g: 120,
    protein_per_100g: 4.4,
    carbs_per_100g: 21,
    fat_per_100g: 1.9,
    fiber_per_100g: 2.8,
  },
  {
    item_key: "bulgur",
    name_fr: "Blé bulgur (cuit)",
    category_l1: "carbs",
    category_l2: "cereales",
    kcal_per_100g: 83,
    protein_per_100g: 3.1,
    carbs_per_100g: 19,
    fat_per_100g: 0.2,
    fiber_per_100g: 4.5,
  },
  {
    item_key: "barley",
    name_fr: "Orge perlé (cuit)",
    category_l1: "carbs",
    category_l2: "cereales",
    kcal_per_100g: 123,
    protein_per_100g: 2.3,
    carbs_per_100g: 28,
    fat_per_100g: 0.4,
    fiber_per_100g: 3.8,
  },

  // ──────────────────────────────────────────────
  // GLUCIDES — Féculents
  // ──────────────────────────────────────────────
  {
    item_key: "white-potato",
    name_fr: "Pomme de terre (cuite vapeur)",
    category_l1: "carbs",
    category_l2: "fecules",
    kcal_per_100g: 87,
    protein_per_100g: 1.9,
    carbs_per_100g: 20,
    fat_per_100g: 0.1,
    fiber_per_100g: 1.8,
  },
  {
    item_key: "sweet-potato",
    name_fr: "Patate douce (cuite)",
    category_l1: "carbs",
    category_l2: "fecules",
    kcal_per_100g: 86,
    protein_per_100g: 1.6,
    carbs_per_100g: 20,
    fat_per_100g: 0.1,
    fiber_per_100g: 3,
  },
  {
    item_key: "pasta-white",
    name_fr: "Pâtes blanches (cuites)",
    category_l1: "carbs",
    category_l2: "fecules",
    kcal_per_100g: 158,
    protein_per_100g: 5.8,
    carbs_per_100g: 31,
    fat_per_100g: 0.9,
    fiber_per_100g: 1.8,
  },
  {
    item_key: "pasta-whole",
    name_fr: "Pâtes complètes (cuites)",
    category_l1: "carbs",
    category_l2: "fecules",
    kcal_per_100g: 149,
    protein_per_100g: 5.5,
    carbs_per_100g: 29,
    fat_per_100g: 1,
    fiber_per_100g: 4,
  },

  // ──────────────────────────────────────────────
  // GLUCIDES — Pain
  // ──────────────────────────────────────────────
  {
    item_key: "white-bread",
    name_fr: "Pain blanc",
    category_l1: "carbs",
    category_l2: "pain",
    kcal_per_100g: 265,
    protein_per_100g: 9,
    carbs_per_100g: 51,
    fat_per_100g: 3.2,
    fiber_per_100g: 2.7,
  },
  {
    item_key: "whole-bread",
    name_fr: "Pain complet",
    category_l1: "carbs",
    category_l2: "pain",
    kcal_per_100g: 247,
    protein_per_100g: 8.5,
    carbs_per_100g: 44,
    fat_per_100g: 3.5,
    fiber_per_100g: 7,
  },
  {
    item_key: "rye-bread",
    name_fr: "Pain de seigle",
    category_l1: "carbs",
    category_l2: "pain",
    kcal_per_100g: 259,
    protein_per_100g: 8.5,
    carbs_per_100g: 48,
    fat_per_100g: 3.3,
    fiber_per_100g: 6.2,
  },
  {
    item_key: "tortilla-wheat",
    name_fr: "Tortilla blé",
    category_l1: "carbs",
    category_l2: "pain",
    kcal_per_100g: 312,
    protein_per_100g: 8.9,
    carbs_per_100g: 49,
    fat_per_100g: 8.5,
    fiber_per_100g: 3,
  },

  // ──────────────────────────────────────────────
  // GLUCIDES — Légumineuses
  // ──────────────────────────────────────────────
  {
    item_key: "lentils",
    name_fr: "Lentilles (cuites)",
    category_l1: "carbs",
    category_l2: "legumineuses",
    kcal_per_100g: 116,
    protein_per_100g: 9,
    carbs_per_100g: 20,
    fat_per_100g: 0.4,
    fiber_per_100g: 7.9,
  },
  {
    item_key: "chickpeas",
    name_fr: "Pois chiches (cuits)",
    category_l1: "carbs",
    category_l2: "legumineuses",
    kcal_per_100g: 164,
    protein_per_100g: 8.9,
    carbs_per_100g: 27,
    fat_per_100g: 2.6,
    fiber_per_100g: 7.6,
  },
  {
    item_key: "kidney-beans",
    name_fr: "Haricots rouges (cuits)",
    category_l1: "carbs",
    category_l2: "legumineuses",
    kcal_per_100g: 127,
    protein_per_100g: 8.7,
    carbs_per_100g: 23,
    fat_per_100g: 0.5,
    fiber_per_100g: 7.4,
  },
  {
    item_key: "black-beans",
    name_fr: "Haricots noirs (cuits)",
    category_l1: "carbs",
    category_l2: "legumineuses",
    kcal_per_100g: 132,
    protein_per_100g: 8.9,
    carbs_per_100g: 24,
    fat_per_100g: 0.5,
    fiber_per_100g: 8.7,
  },

  // ──────────────────────────────────────────────
  // LÉGUMES — Feuilles
  // ──────────────────────────────────────────────
  {
    item_key: "spinach",
    name_fr: "Épinards (crus)",
    category_l1: "vegetables",
    category_l2: "feuilles",
    kcal_per_100g: 23,
    protein_per_100g: 2.9,
    carbs_per_100g: 3.6,
    fat_per_100g: 0.4,
    fiber_per_100g: 2.2,
  },
  {
    item_key: "lettuce",
    name_fr: "Salade verte",
    category_l1: "vegetables",
    category_l2: "feuilles",
    kcal_per_100g: 15,
    protein_per_100g: 1.4,
    carbs_per_100g: 2.2,
    fat_per_100g: 0.2,
    fiber_per_100g: 1.3,
  },
  {
    item_key: "arugula",
    name_fr: "Roquette",
    category_l1: "vegetables",
    category_l2: "feuilles",
    kcal_per_100g: 25,
    protein_per_100g: 2.6,
    carbs_per_100g: 3.7,
    fat_per_100g: 0.7,
    fiber_per_100g: 1.6,
  },
  {
    item_key: "kale",
    name_fr: "Chou frisé (kale)",
    category_l1: "vegetables",
    category_l2: "feuilles",
    kcal_per_100g: 49,
    protein_per_100g: 4.3,
    carbs_per_100g: 9,
    fat_per_100g: 0.9,
    fiber_per_100g: 3.6,
  },

  // ──────────────────────────────────────────────
  // LÉGUMES — Crucifères
  // ──────────────────────────────────────────────
  {
    item_key: "broccoli",
    name_fr: "Brocoli (cuit)",
    category_l1: "vegetables",
    category_l2: "cruciferes",
    kcal_per_100g: 35,
    protein_per_100g: 2.4,
    carbs_per_100g: 7,
    fat_per_100g: 0.4,
    fiber_per_100g: 3.3,
  },
  {
    item_key: "cauliflower",
    name_fr: "Chou-fleur (cuit)",
    category_l1: "vegetables",
    category_l2: "cruciferes",
    kcal_per_100g: 23,
    protein_per_100g: 1.9,
    carbs_per_100g: 5,
    fat_per_100g: 0.3,
    fiber_per_100g: 2,
  },
  {
    item_key: "cabbage",
    name_fr: "Chou blanc (cru)",
    category_l1: "vegetables",
    category_l2: "cruciferes",
    kcal_per_100g: 25,
    protein_per_100g: 1.3,
    carbs_per_100g: 5.8,
    fat_per_100g: 0.1,
    fiber_per_100g: 2.5,
  },

  // ──────────────────────────────────────────────
  // LÉGUMES — Autres
  // ──────────────────────────────────────────────
  {
    item_key: "zucchini",
    name_fr: "Courgette (crue)",
    category_l1: "vegetables",
    category_l2: "autres-legumes",
    kcal_per_100g: 17,
    protein_per_100g: 1.2,
    carbs_per_100g: 3.1,
    fat_per_100g: 0.3,
    fiber_per_100g: 1,
  },
  {
    item_key: "bell-pepper",
    name_fr: "Poivron rouge (cru)",
    category_l1: "vegetables",
    category_l2: "autres-legumes",
    kcal_per_100g: 31,
    protein_per_100g: 1,
    carbs_per_100g: 7.3,
    fat_per_100g: 0.3,
    fiber_per_100g: 2.1,
  },
  {
    item_key: "tomato",
    name_fr: "Tomate (crue)",
    category_l1: "vegetables",
    category_l2: "autres-legumes",
    kcal_per_100g: 18,
    protein_per_100g: 0.9,
    carbs_per_100g: 3.9,
    fat_per_100g: 0.2,
    fiber_per_100g: 1.2,
  },
  {
    item_key: "carrot",
    name_fr: "Carotte (crue)",
    category_l1: "vegetables",
    category_l2: "autres-legumes",
    kcal_per_100g: 41,
    protein_per_100g: 0.9,
    carbs_per_100g: 10,
    fat_per_100g: 0.2,
    fiber_per_100g: 2.8,
  },
  {
    item_key: "cucumber",
    name_fr: "Concombre (cru)",
    category_l1: "vegetables",
    category_l2: "autres-legumes",
    kcal_per_100g: 16,
    protein_per_100g: 0.7,
    carbs_per_100g: 3.6,
    fat_per_100g: 0.1,
    fiber_per_100g: 0.5,
  },
  {
    item_key: "onion",
    name_fr: "Oignon (cru)",
    category_l1: "vegetables",
    category_l2: "autres-legumes",
    kcal_per_100g: 40,
    protein_per_100g: 1.1,
    carbs_per_100g: 9.3,
    fat_per_100g: 0.1,
    fiber_per_100g: 1.7,
  },
  {
    item_key: "mushrooms",
    name_fr: "Champignons (crus)",
    category_l1: "vegetables",
    category_l2: "autres-legumes",
    kcal_per_100g: 22,
    protein_per_100g: 3.1,
    carbs_per_100g: 3.3,
    fat_per_100g: 0.3,
    fiber_per_100g: 1,
  },
  {
    item_key: "asparagus",
    name_fr: "Asperges (cuites)",
    category_l1: "vegetables",
    category_l2: "autres-legumes",
    kcal_per_100g: 20,
    protein_per_100g: 2.2,
    carbs_per_100g: 3.9,
    fat_per_100g: 0.1,
    fiber_per_100g: 2.1,
  },
  {
    item_key: "green-beans",
    name_fr: "Haricots verts (cuits)",
    category_l1: "vegetables",
    category_l2: "autres-legumes",
    kcal_per_100g: 31,
    protein_per_100g: 1.8,
    carbs_per_100g: 7.1,
    fat_per_100g: 0.1,
    fiber_per_100g: 3.4,
  },
  {
    item_key: "eggplant",
    name_fr: "Aubergine (cuite)",
    category_l1: "vegetables",
    category_l2: "autres-legumes",
    kcal_per_100g: 33,
    protein_per_100g: 0.8,
    carbs_per_100g: 8.7,
    fat_per_100g: 0.2,
    fiber_per_100g: 2.5,
  },

  // ──────────────────────────────────────────────
  // FRUITS — Frais
  // ──────────────────────────────────────────────
  {
    item_key: "banana",
    name_fr: "Banane",
    category_l1: "fruits",
    category_l2: "frais",
    kcal_per_100g: 89,
    protein_per_100g: 1.1,
    carbs_per_100g: 23,
    fat_per_100g: 0.3,
    fiber_per_100g: 2.6,
  },
  {
    item_key: "apple",
    name_fr: "Pomme",
    category_l1: "fruits",
    category_l2: "frais",
    kcal_per_100g: 52,
    protein_per_100g: 0.3,
    carbs_per_100g: 14,
    fat_per_100g: 0.2,
    fiber_per_100g: 2.4,
  },
  {
    item_key: "orange",
    name_fr: "Orange",
    category_l1: "fruits",
    category_l2: "frais",
    kcal_per_100g: 47,
    protein_per_100g: 0.9,
    carbs_per_100g: 12,
    fat_per_100g: 0.1,
    fiber_per_100g: 2.4,
  },
  {
    item_key: "strawberries",
    name_fr: "Fraises",
    category_l1: "fruits",
    category_l2: "frais",
    kcal_per_100g: 32,
    protein_per_100g: 0.7,
    carbs_per_100g: 7.7,
    fat_per_100g: 0.3,
    fiber_per_100g: 2,
  },
  {
    item_key: "blueberries",
    name_fr: "Myrtilles",
    category_l1: "fruits",
    category_l2: "frais",
    kcal_per_100g: 57,
    protein_per_100g: 0.7,
    carbs_per_100g: 14,
    fat_per_100g: 0.3,
    fiber_per_100g: 2.4,
  },
  {
    item_key: "mango",
    name_fr: "Mangue",
    category_l1: "fruits",
    category_l2: "frais",
    kcal_per_100g: 60,
    protein_per_100g: 0.8,
    carbs_per_100g: 15,
    fat_per_100g: 0.4,
    fiber_per_100g: 1.6,
  },
  {
    item_key: "kiwi",
    name_fr: "Kiwi",
    category_l1: "fruits",
    category_l2: "frais",
    kcal_per_100g: 61,
    protein_per_100g: 1.1,
    carbs_per_100g: 15,
    fat_per_100g: 0.5,
    fiber_per_100g: 3,
  },
  {
    item_key: "grapes",
    name_fr: "Raisins",
    category_l1: "fruits",
    category_l2: "frais",
    kcal_per_100g: 69,
    protein_per_100g: 0.7,
    carbs_per_100g: 18,
    fat_per_100g: 0.2,
    fiber_per_100g: 0.9,
  },
  {
    item_key: "pear",
    name_fr: "Poire",
    category_l1: "fruits",
    category_l2: "frais",
    kcal_per_100g: 57,
    protein_per_100g: 0.4,
    carbs_per_100g: 15,
    fat_per_100g: 0.1,
    fiber_per_100g: 3.1,
  },
  {
    item_key: "watermelon",
    name_fr: "Pastèque",
    category_l1: "fruits",
    category_l2: "frais",
    kcal_per_100g: 30,
    protein_per_100g: 0.6,
    carbs_per_100g: 7.6,
    fat_per_100g: 0.2,
    fiber_per_100g: 0.4,
  },

  // ──────────────────────────────────────────────
  // FRUITS — Secs
  // ──────────────────────────────────────────────
  {
    item_key: "dates",
    name_fr: "Dattes",
    category_l1: "fruits",
    category_l2: "secs",
    kcal_per_100g: 277,
    protein_per_100g: 1.8,
    carbs_per_100g: 75,
    fat_per_100g: 0.2,
    fiber_per_100g: 6.7,
  },
  {
    item_key: "dried-apricots",
    name_fr: "Abricots secs",
    category_l1: "fruits",
    category_l2: "secs",
    kcal_per_100g: 241,
    protein_per_100g: 3.4,
    carbs_per_100g: 63,
    fat_per_100g: 0.5,
    fiber_per_100g: 7.3,
  },
  {
    item_key: "raisins",
    name_fr: "Raisins secs",
    category_l1: "fruits",
    category_l2: "secs",
    kcal_per_100g: 299,
    protein_per_100g: 3.1,
    carbs_per_100g: 79,
    fat_per_100g: 0.5,
    fiber_per_100g: 3.7,
  },

  // ──────────────────────────────────────────────
  // LIPIDES — Huiles
  // ──────────────────────────────────────────────
  {
    item_key: "olive-oil",
    name_fr: "Huile d'olive",
    category_l1: "fats",
    category_l2: "huiles",
    kcal_per_100g: 884,
    protein_per_100g: 0,
    carbs_per_100g: 0,
    fat_per_100g: 100,
    fiber_per_100g: 0,
  },
  {
    item_key: "coconut-oil",
    name_fr: "Huile de coco",
    category_l1: "fats",
    category_l2: "huiles",
    kcal_per_100g: 862,
    protein_per_100g: 0,
    carbs_per_100g: 0,
    fat_per_100g: 100,
    fiber_per_100g: 0,
  },
  {
    item_key: "rapeseed-oil",
    name_fr: "Huile de colza",
    category_l1: "fats",
    category_l2: "huiles",
    kcal_per_100g: 884,
    protein_per_100g: 0,
    carbs_per_100g: 0,
    fat_per_100g: 100,
    fiber_per_100g: 0,
  },

  // ──────────────────────────────────────────────
  // LIPIDES — Noix & Graines
  // ──────────────────────────────────────────────
  {
    item_key: "almonds",
    name_fr: "Amandes",
    category_l1: "fats",
    category_l2: "noix-graines",
    kcal_per_100g: 579,
    protein_per_100g: 21,
    carbs_per_100g: 22,
    fat_per_100g: 50,
    fiber_per_100g: 12,
  },
  {
    item_key: "walnuts",
    name_fr: "Noix",
    category_l1: "fats",
    category_l2: "noix-graines",
    kcal_per_100g: 654,
    protein_per_100g: 15,
    carbs_per_100g: 14,
    fat_per_100g: 65,
    fiber_per_100g: 6.7,
  },
  {
    item_key: "cashews",
    name_fr: "Noix de cajou",
    category_l1: "fats",
    category_l2: "noix-graines",
    kcal_per_100g: 553,
    protein_per_100g: 18,
    carbs_per_100g: 30,
    fat_per_100g: 44,
    fiber_per_100g: 3.3,
  },
  {
    item_key: "chia-seeds",
    name_fr: "Graines de chia",
    category_l1: "fats",
    category_l2: "noix-graines",
    kcal_per_100g: 486,
    protein_per_100g: 17,
    carbs_per_100g: 42,
    fat_per_100g: 31,
    fiber_per_100g: 34,
  },
  {
    item_key: "flax-seeds",
    name_fr: "Graines de lin",
    category_l1: "fats",
    category_l2: "noix-graines",
    kcal_per_100g: 534,
    protein_per_100g: 18,
    carbs_per_100g: 29,
    fat_per_100g: 42,
    fiber_per_100g: 27,
  },
  {
    item_key: "pumpkin-seeds",
    name_fr: "Graines de courge",
    category_l1: "fats",
    category_l2: "noix-graines",
    kcal_per_100g: 559,
    protein_per_100g: 30,
    carbs_per_100g: 11,
    fat_per_100g: 49,
    fiber_per_100g: 6,
  },

  // ──────────────────────────────────────────────
  // LIPIDES — Autres
  // ──────────────────────────────────────────────
  {
    item_key: "butter",
    name_fr: "Beurre",
    category_l1: "fats",
    category_l2: "autres-lipides",
    kcal_per_100g: 717,
    protein_per_100g: 0.9,
    carbs_per_100g: 0.1,
    fat_per_100g: 81,
    fiber_per_100g: 0,
  },
  {
    item_key: "butter-baratte",
    name_fr: "Beurre de baratte",
    category_l1: "fats",
    category_l2: "autres-lipides",
    kcal_per_100g: 733,
    protein_per_100g: 0.8,
    carbs_per_100g: 0.1,
    fat_per_100g: 82,
    fiber_per_100g: 0,
  },
  {
    item_key: "butter-salted",
    name_fr: "Beurre demi-sel",
    category_l1: "fats",
    category_l2: "autres-lipides",
    kcal_per_100g: 717,
    protein_per_100g: 0.9,
    carbs_per_100g: 0.1,
    fat_per_100g: 81,
    fiber_per_100g: 0,
  },
  {
    item_key: "ghee",
    name_fr: "Ghee (beurre clarifié)",
    category_l1: "fats",
    category_l2: "autres-lipides",
    kcal_per_100g: 900,
    protein_per_100g: 0,
    carbs_per_100g: 0,
    fat_per_100g: 100,
    fiber_per_100g: 0,
  },
  {
    item_key: "almond-butter",
    name_fr: "Beurre d'amande",
    category_l1: "fats",
    category_l2: "autres-lipides",
    kcal_per_100g: 614,
    protein_per_100g: 21,
    carbs_per_100g: 19,
    fat_per_100g: 56,
    fiber_per_100g: 10,
  },
  {
    item_key: "peanut-butter",
    name_fr: "Beurre de cacahuète",
    category_l1: "fats",
    category_l2: "autres-lipides",
    kcal_per_100g: 588,
    protein_per_100g: 25,
    carbs_per_100g: 20,
    fat_per_100g: 50,
    fiber_per_100g: 6,
  },
  {
    item_key: "avocado",
    name_fr: "Avocat",
    category_l1: "fats",
    category_l2: "autres-lipides",
    kcal_per_100g: 160,
    protein_per_100g: 2,
    carbs_per_100g: 9,
    fat_per_100g: 15,
    fiber_per_100g: 7,
  },
  {
    item_key: "dark-chocolate-85",
    name_fr: "Chocolat noir 85%",
    category_l1: "fats",
    category_l2: "autres-lipides",
    kcal_per_100g: 598,
    protein_per_100g: 12,
    carbs_per_100g: 24,
    fat_per_100g: 43,
    fiber_per_100g: 11,
  },
  {
    item_key: "peanuts",
    name_fr: "Cacahuètes (grillées)",
    category_l1: "fats",
    category_l2: "noix-graines",
    kcal_per_100g: 567,
    protein_per_100g: 26,
    carbs_per_100g: 16,
    fat_per_100g: 49,
    fiber_per_100g: 8.5,
  },
  {
    item_key: "hazelnuts",
    name_fr: "Noisettes",
    category_l1: "fats",
    category_l2: "noix-graines",
    kcal_per_100g: 628,
    protein_per_100g: 15,
    carbs_per_100g: 17,
    fat_per_100g: 61,
    fiber_per_100g: 9.7,
  },
  {
    item_key: "sunflower-seeds",
    name_fr: "Graines de tournesol",
    category_l1: "fats",
    category_l2: "noix-graines",
    kcal_per_100g: 584,
    protein_per_100g: 21,
    carbs_per_100g: 20,
    fat_per_100g: 51,
    fiber_per_100g: 8.6,
  },

  // ──────────────────────────────────────────────
  // PROTÉINES — Fromages
  // ──────────────────────────────────────────────
  {
    item_key: "emmental",
    name_fr: "Emmental",
    category_l1: "proteins",
    category_l2: "laitiers",
    kcal_per_100g: 382,
    protein_per_100g: 29,
    carbs_per_100g: 1.5,
    fat_per_100g: 30,
    fiber_per_100g: 0,
  },
  {
    item_key: "comte",
    name_fr: "Comté",
    category_l1: "proteins",
    category_l2: "laitiers",
    kcal_per_100g: 413,
    protein_per_100g: 29,
    carbs_per_100g: 0.4,
    fat_per_100g: 34,
    fiber_per_100g: 0,
  },
  {
    item_key: "gruyere",
    name_fr: "Gruyère",
    category_l1: "proteins",
    category_l2: "laitiers",
    kcal_per_100g: 413,
    protein_per_100g: 29,
    carbs_per_100g: 0.4,
    fat_per_100g: 34,
    fiber_per_100g: 0,
  },
  {
    item_key: "camembert",
    name_fr: "Camembert",
    category_l1: "proteins",
    category_l2: "laitiers",
    kcal_per_100g: 263,
    protein_per_100g: 19,
    carbs_per_100g: 0.5,
    fat_per_100g: 21,
    fiber_per_100g: 0,
  },
  {
    item_key: "brie",
    name_fr: "Brie",
    category_l1: "proteins",
    category_l2: "laitiers",
    kcal_per_100g: 334,
    protein_per_100g: 21,
    carbs_per_100g: 0.5,
    fat_per_100g: 27,
    fiber_per_100g: 0,
  },
  {
    item_key: "cheddar",
    name_fr: "Cheddar",
    category_l1: "proteins",
    category_l2: "laitiers",
    kcal_per_100g: 402,
    protein_per_100g: 25,
    carbs_per_100g: 1.3,
    fat_per_100g: 33,
    fiber_per_100g: 0,
  },
  {
    item_key: "cream-cheese",
    name_fr: "Fromage frais (type Philadelphia)",
    category_l1: "proteins",
    category_l2: "laitiers",
    kcal_per_100g: 342,
    protein_per_100g: 6,
    carbs_per_100g: 4,
    fat_per_100g: 34,
    fiber_per_100g: 0,
  },
  {
    item_key: "creme-fraiche",
    name_fr: "Crème fraîche entière",
    category_l1: "fats",
    category_l2: "autres-lipides",
    kcal_per_100g: 300,
    protein_per_100g: 2.5,
    carbs_per_100g: 3.5,
    fat_per_100g: 30,
    fiber_per_100g: 0,
  },
  {
    item_key: "creme-fraiche-light",
    name_fr: "Crème fraîche allégée",
    category_l1: "fats",
    category_l2: "autres-lipides",
    kcal_per_100g: 168,
    protein_per_100g: 3,
    carbs_per_100g: 4,
    fat_per_100g: 15,
    fiber_per_100g: 0,
  },

  // ──────────────────────────────────────────────
  // GLUCIDES — Féculents (ajouts)
  // ──────────────────────────────────────────────
  {
    item_key: "french-fries",
    name_fr: "Frites (cuites four ou friture)",
    category_l1: "carbs",
    category_l2: "fecules",
    kcal_per_100g: 274,
    protein_per_100g: 3.4,
    carbs_per_100g: 35,
    fat_per_100g: 13,
    fiber_per_100g: 3.3,
  },
  {
    item_key: "potato-mashed",
    name_fr: "Purée de pomme de terre",
    category_l1: "carbs",
    category_l2: "fecules",
    kcal_per_100g: 90,
    protein_per_100g: 1.9,
    carbs_per_100g: 16,
    fat_per_100g: 2.5,
    fiber_per_100g: 1.5,
  },
  {
    item_key: "gnocchi",
    name_fr: "Gnocchis (cuits)",
    category_l1: "carbs",
    category_l2: "fecules",
    kcal_per_100g: 131,
    protein_per_100g: 3,
    carbs_per_100g: 27,
    fat_per_100g: 0.8,
    fiber_per_100g: 1.5,
  },

  // ──────────────────────────────────────────────
  // EXTRAS — Snacks salés
  // ──────────────────────────────────────────────
  {
    item_key: "chips-potato",
    name_fr: "Chips (pomme de terre)",
    category_l1: "extras",
    category_l2: "snacks-sales",
    kcal_per_100g: 536,
    protein_per_100g: 6,
    carbs_per_100g: 53,
    fat_per_100g: 34,
    fiber_per_100g: 4.7,
  },
  {
    item_key: "crackers-wheat",
    name_fr: "Crackers / biscuits salés",
    category_l1: "extras",
    category_l2: "snacks-sales",
    kcal_per_100g: 430,
    protein_per_100g: 8,
    carbs_per_100g: 66,
    fat_per_100g: 16,
    fiber_per_100g: 2.5,
  },
  {
    item_key: "popcorn-plain",
    name_fr: "Popcorn (nature)",
    category_l1: "extras",
    category_l2: "snacks-sales",
    kcal_per_100g: 375,
    protein_per_100g: 11,
    carbs_per_100g: 78,
    fat_per_100g: 4.3,
    fiber_per_100g: 15,
  },
  {
    item_key: "pretzels",
    name_fr: "Bretzels",
    category_l1: "extras",
    category_l2: "snacks-sales",
    kcal_per_100g: 380,
    protein_per_100g: 9,
    carbs_per_100g: 80,
    fat_per_100g: 3,
    fiber_per_100g: 2.5,
  },

  // ──────────────────────────────────────────────
  // EXTRAS — Snacks sucrés
  // ──────────────────────────────────────────────
  {
    item_key: "cereal-bar",
    name_fr: "Barre de céréales",
    category_l1: "extras",
    category_l2: "snacks-sucres",
    kcal_per_100g: 380,
    protein_per_100g: 6,
    carbs_per_100g: 66,
    fat_per_100g: 11,
    fiber_per_100g: 4,
  },
  {
    item_key: "protein-bar",
    name_fr: "Barre protéinée",
    category_l1: "extras",
    category_l2: "snacks-sucres",
    kcal_per_100g: 380,
    protein_per_100g: 30,
    carbs_per_100g: 38,
    fat_per_100g: 10,
    fiber_per_100g: 3,
  },
  {
    item_key: "biscuit-sec",
    name_fr: "Biscuits secs (type petit-beurre)",
    category_l1: "extras",
    category_l2: "snacks-sucres",
    kcal_per_100g: 447,
    protein_per_100g: 7.1,
    carbs_per_100g: 70,
    fat_per_100g: 15,
    fiber_per_100g: 2.5,
  },
  {
    item_key: "milk-chocolate",
    name_fr: "Chocolat au lait",
    category_l1: "extras",
    category_l2: "snacks-sucres",
    kcal_per_100g: 535,
    protein_per_100g: 7.6,
    carbs_per_100g: 60,
    fat_per_100g: 30,
    fiber_per_100g: 1.5,
  },
  {
    item_key: "fruit-compote",
    name_fr: "Compote de pommes (sans sucre ajouté)",
    category_l1: "extras",
    category_l2: "snacks-sucres",
    kcal_per_100g: 47,
    protein_per_100g: 0.3,
    carbs_per_100g: 12,
    fat_per_100g: 0.1,
    fiber_per_100g: 1.4,
  },

  // ──────────────────────────────────────────────
  // GLUCIDES — Céréales (ajouts)
  // ──────────────────────────────────────────────
  {
    item_key: "couscous",
    name_fr: "Couscous (cuit)",
    category_l1: "carbs",
    category_l2: "cereales",
    kcal_per_100g: 112,
    protein_per_100g: 3.8,
    carbs_per_100g: 23,
    fat_per_100g: 0.2,
    fiber_per_100g: 1.4,
  },
  {
    item_key: "rice-basmati",
    name_fr: "Riz basmati (cuit)",
    category_l1: "carbs",
    category_l2: "cereales",
    kcal_per_100g: 121,
    protein_per_100g: 2.7,
    carbs_per_100g: 27,
    fat_per_100g: 0.3,
    fiber_per_100g: 0.5,
  },
  {
    item_key: "rice-jasmine",
    name_fr: "Riz jasmin (cuit)",
    category_l1: "carbs",
    category_l2: "cereales",
    kcal_per_100g: 129,
    protein_per_100g: 2.5,
    carbs_per_100g: 28,
    fat_per_100g: 0.2,
    fiber_per_100g: 0.4,
  },
  {
    item_key: "pasta-fresh",
    name_fr: "Pâtes fraîches (cuites)",
    category_l1: "carbs",
    category_l2: "fecules",
    kcal_per_100g: 131,
    protein_per_100g: 5.5,
    carbs_per_100g: 24,
    fat_per_100g: 1.5,
    fiber_per_100g: 1.2,
  },
  {
    item_key: "rice-cakes",
    name_fr: "Galettes de riz",
    category_l1: "carbs",
    category_l2: "cereales",
    kcal_per_100g: 387,
    protein_per_100g: 7.9,
    carbs_per_100g: 81,
    fat_per_100g: 3.5,
    fiber_per_100g: 4,
  },
  {
    item_key: "muesli",
    name_fr: "Muesli nature (sans sucre ajouté)",
    category_l1: "carbs",
    category_l2: "cereales",
    kcal_per_100g: 368,
    protein_per_100g: 10,
    carbs_per_100g: 59,
    fat_per_100g: 7,
    fiber_per_100g: 7,
  },

  // ──────────────────────────────────────────────
  // EXTRAS — Sauces & Condiments
  // ──────────────────────────────────────────────
  {
    item_key: "ketchup",
    name_fr: "Ketchup",
    category_l1: "extras",
    category_l2: "sauces",
    kcal_per_100g: 101,
    protein_per_100g: 1.1,
    carbs_per_100g: 25,
    fat_per_100g: 0.1,
    fiber_per_100g: 0.3,
  },
  {
    item_key: "mayonnaise",
    name_fr: "Mayonnaise",
    category_l1: "extras",
    category_l2: "sauces",
    kcal_per_100g: 680,
    protein_per_100g: 1.1,
    carbs_per_100g: 2.2,
    fat_per_100g: 75,
    fiber_per_100g: 0,
  },
  {
    item_key: "soy-sauce",
    name_fr: "Sauce soja",
    category_l1: "extras",
    category_l2: "sauces",
    kcal_per_100g: 53,
    protein_per_100g: 8.1,
    carbs_per_100g: 4.9,
    fat_per_100g: 0.1,
    fiber_per_100g: 0.8,
  },
  {
    item_key: "mustard",
    name_fr: "Moutarde",
    category_l1: "extras",
    category_l2: "sauces",
    kcal_per_100g: 66,
    protein_per_100g: 4.4,
    carbs_per_100g: 5.7,
    fat_per_100g: 3.3,
    fiber_per_100g: 3.2,
  },
  {
    item_key: "tomato-sauce",
    name_fr: "Sauce tomate (base)",
    category_l1: "extras",
    category_l2: "sauces",
    kcal_per_100g: 38,
    protein_per_100g: 1.6,
    carbs_per_100g: 7.7,
    fat_per_100g: 0.5,
    fiber_per_100g: 1.4,
  },
  {
    item_key: "vinaigrette",
    name_fr: "Vinaigrette (huile + vinaigre)",
    category_l1: "extras",
    category_l2: "sauces",
    kcal_per_100g: 460,
    protein_per_100g: 0,
    carbs_per_100g: 3,
    fat_per_100g: 50,
    fiber_per_100g: 0,
  },

  // ──────────────────────────────────────────────
  // PROTÉINES — Laitiers (laits de vache)
  // ──────────────────────────────────────────────
  {
    item_key: "whole-milk",
    name_fr: "Lait entier",
    category_l1: "proteins",
    category_l2: "laitiers",
    kcal_per_100g: 61,
    protein_per_100g: 3.2,
    carbs_per_100g: 4.8,
    fat_per_100g: 3.3,
    fiber_per_100g: 0,
  },
  {
    item_key: "skim-milk",
    name_fr: "Lait écrémé",
    category_l1: "proteins",
    category_l2: "laitiers",
    kcal_per_100g: 34,
    protein_per_100g: 3.4,
    carbs_per_100g: 5,
    fat_per_100g: 0.1,
    fiber_per_100g: 0,
  },
  {
    item_key: "parmesan",
    name_fr: "Parmesan",
    category_l1: "proteins",
    category_l2: "laitiers",
    kcal_per_100g: 431,
    protein_per_100g: 38,
    carbs_per_100g: 3.2,
    fat_per_100g: 29,
    fiber_per_100g: 0,
  },
  {
    item_key: "mozzarella",
    name_fr: "Mozzarella",
    category_l1: "proteins",
    category_l2: "laitiers",
    kcal_per_100g: 280,
    protein_per_100g: 28,
    carbs_per_100g: 2.2,
    fat_per_100g: 17,
    fiber_per_100g: 0,
  },

  // ──────────────────────────────────────────────
  // BOISSONS — Chaudes
  // ──────────────────────────────────────────────
  {
    item_key: "coffee-black",
    name_fr: "Café noir",
    category_l1: "drinks",
    category_l2: "chauds",
    kcal_per_100g: 2,
    protein_per_100g: 0.3,
    carbs_per_100g: 0,
    fat_per_100g: 0,
    fiber_per_100g: 0,
  },
  {
    item_key: "tea-black",
    name_fr: "Thé noir (sans sucre)",
    category_l1: "drinks",
    category_l2: "chauds",
    kcal_per_100g: 1,
    protein_per_100g: 0.1,
    carbs_per_100g: 0.3,
    fat_per_100g: 0,
    fiber_per_100g: 0,
  },
  {
    item_key: "tea-green",
    name_fr: "Thé vert (sans sucre)",
    category_l1: "drinks",
    category_l2: "chauds",
    kcal_per_100g: 1,
    protein_per_100g: 0.2,
    carbs_per_100g: 0.2,
    fat_per_100g: 0,
    fiber_per_100g: 0,
  },

  // ──────────────────────────────────────────────
  // BOISSONS — Laits végétaux
  // ──────────────────────────────────────────────
  {
    item_key: "oat-milk",
    name_fr: "Lait d'avoine",
    category_l1: "drinks",
    category_l2: "laits-vegetaux",
    kcal_per_100g: 45,
    protein_per_100g: 1,
    carbs_per_100g: 9,
    fat_per_100g: 1.5,
    fiber_per_100g: 0.8,
  },
  {
    item_key: "almond-milk-unsweetened",
    name_fr: "Lait d'amande (sans sucre)",
    category_l1: "drinks",
    category_l2: "laits-vegetaux",
    kcal_per_100g: 17,
    protein_per_100g: 0.6,
    carbs_per_100g: 0.6,
    fat_per_100g: 1.4,
    fiber_per_100g: 0.2,
  },
  {
    item_key: "soy-milk",
    name_fr: "Lait de soja (non sucré)",
    category_l1: "drinks",
    category_l2: "laits-vegetaux",
    kcal_per_100g: 33,
    protein_per_100g: 3.3,
    carbs_per_100g: 1.8,
    fat_per_100g: 1.9,
    fiber_per_100g: 0.2,
  },
  {
    item_key: "coconut-milk-light",
    name_fr: "Lait de coco allégé",
    category_l1: "drinks",
    category_l2: "laits-vegetaux",
    kcal_per_100g: 68,
    protein_per_100g: 1,
    carbs_per_100g: 2.7,
    fat_per_100g: 6,
    fiber_per_100g: 0,
  },

  // ──────────────────────────────────────────────
  // BOISSONS — Jus & Smoothies
  // ──────────────────────────────────────────────
  {
    item_key: "orange-juice",
    name_fr: "Jus d'orange (pressé)",
    category_l1: "drinks",
    category_l2: "jus-smoothies",
    kcal_per_100g: 45,
    protein_per_100g: 0.7,
    carbs_per_100g: 10,
    fat_per_100g: 0.2,
    fiber_per_100g: 0.2,
  },
  {
    item_key: "apple-juice",
    name_fr: "Jus de pomme (pur jus)",
    category_l1: "drinks",
    category_l2: "jus-smoothies",
    kcal_per_100g: 46,
    protein_per_100g: 0.1,
    carbs_per_100g: 11,
    fat_per_100g: 0.1,
    fiber_per_100g: 0.1,
  },
  {
    item_key: "lemon-juice",
    name_fr: "Jus de citron (pressé)",
    category_l1: "drinks",
    category_l2: "jus-smoothies",
    kcal_per_100g: 29,
    protein_per_100g: 1.1,
    carbs_per_100g: 9,
    fat_per_100g: 0.3,
    fiber_per_100g: 0.3,
  },

  // ──────────────────────────────────────────────
  // EXTRAS — Sucres & Tartinades
  // ──────────────────────────────────────────────
  {
    item_key: "jam",
    name_fr: "Confiture",
    category_l1: "extras",
    category_l2: "sucres",
    kcal_per_100g: 250,
    protein_per_100g: 0.4,
    carbs_per_100g: 65,
    fat_per_100g: 0.1,
    fiber_per_100g: 1.1,
  },
  {
    item_key: "honey",
    name_fr: "Miel",
    category_l1: "extras",
    category_l2: "sucres",
    kcal_per_100g: 304,
    protein_per_100g: 0.3,
    carbs_per_100g: 82,
    fat_per_100g: 0,
    fiber_per_100g: 0.2,
  },
  {
    item_key: "maple-syrup",
    name_fr: "Sirop d'érable",
    category_l1: "extras",
    category_l2: "sucres",
    kcal_per_100g: 260,
    protein_per_100g: 0,
    carbs_per_100g: 67,
    fat_per_100g: 0.1,
    fiber_per_100g: 0,
  },
  {
    item_key: "nutella",
    name_fr: "Nutella / pâte à tartiner",
    category_l1: "extras",
    category_l2: "sucres",
    kcal_per_100g: 530,
    protein_per_100g: 6,
    carbs_per_100g: 58,
    fat_per_100g: 31,
    fiber_per_100g: 0,
  },
];

async function main() {
  console.log(`Seeding ${FOOD_ITEMS.length} food items...`);

  const { error } = await supabase
    .from("food_items")
    .upsert(FOOD_ITEMS, { onConflict: "item_key" });

  if (error) {
    console.error("Seed error:", error);
    process.exit(1);
  }

  console.log(`✓ ${FOOD_ITEMS.length} food items seeded successfully`);
}

main();
