-- supabase/migrations/20260520_coach_feedback_ai_draft.sql
-- Add is_ai_draft flag to coach_feedback — marks messages generated by AI (pending coach review)

ALTER TABLE coach_feedback
  ADD COLUMN IF NOT EXISTS is_ai_draft boolean NOT NULL DEFAULT false;

CREATE INDEX IF NOT EXISTS idx_coach_feedback_ai_draft
  ON coach_feedback (coach_id, is_ai_draft)
  WHERE is_ai_draft = true;
